### ISSUE TITLE
Tags Drop Down cut-off

### ISSUE THREAD

**Issue by mbadsey** [chriskyfung/amp-affiliately-jekyll-theme#14]
Was browsing some Jekyll themes, This is a nice one, but noticed the drop down for viewing tags isn’t being shown properly on iPad Pro, Latest release
![65018079-630F-4F51-857E-3B28E82CA327](https://user-images.githubusercontent.com/12601328/127953852-db0bc27a-8a14-47db-85f3-06b35a0f7694.jpeg)

**Comment by chriskyfung** [comment]
> Was browsing some Jekyll themes, This is a nice one, but noticed the drop down for viewing tags isn’t being shown properly on iPad Pro, Latest release
> ![65018079-630F-4F51-857E-3B28E82CA327](https://user-images.githubusercontent.com/12601328/127953852-db0bc27a-8a14-47db-85f3-06b35a0f7694.jpeg)

Hi, mbadsey! Thanks for reporting the issue.
The dropdown shows properly in Chrome on my desktop. I think it just happens on iPad.
Which browser do you use, Safari 14.1.2?

**Comment by chriskyfung** [comment]
Hi @mbadsey,

I tried my best to fix this bug. I saw the dropdown menu shows properly in iOS Simulator.
Could you please let me know if the latest version also works on your iPad? Thanks :)

**Comment by chriskyfung** [comment]
Tested with iPad Air2 (ios 14.1) on [Appetize.io](https://appetize.io/)

![2021-08-29 21-40-16 High Res Screenshot](https://user-images.githubusercontent.com/8746768/131252497-4faa61d1-45c7-453c-a326-9b80d743ab8c.png)
