### ISSUE TITLE
Favicon not showing

### ISSUE THREAD

**Issue by shoaiyb** [chriskyfung/amp-affiliately-jekyll-theme#2]
I change the favicon (I deleted the default favicon and replace with new one with the same link structure '/favicon.png and /favicon.webp') but shows nothing on the home page and when visited posts the default favicon show
And the /tag/, /category/ and/blog/ shows error
And how can I customize 404

**Comment by chriskyfung** [comment]
Regarding the favicon, you can define an absolute URL in the _config.yml, i.e. `favicon: '.../favicon.png'`

**Comment by chriskyfung** [comment]
Since I need the tag, blog, and category to be the base directory after my domain, the paths will mismatch if you're using the theme for a project page, e.g. yourname.github.io/repo123/.

Copy the file `/_layouts/default.html` to your Jekyll repository, and then replace `href="/tag/" to `href="{{site.baseurl}}/tag"` in the file. Repeat the step for /blog and /category. Finally, change `baseurl: '/amp-affiliately-jekyll-theme'` correspondingly in the **_config.yml** file.

**Comment by chriskyfung** [comment]
For the custom 404 pages, please read [Custom 404 Page](https://jekyllrb.com/tutorials/custom-404-page/) in the official Jekyll documentation.

**Comment by shoaiyb** [comment]
> Since I need the tag, blog, and category to be the base directory after my domain, the paths will mismatch if you're using the theme for a project page, e.g. yourname.github.io/repo123/.
> 
> Copy the file `/_layouts/default.html` to your Jekyll repository, and then replace `href="/tag/" to `href="{{site.baseurl}}/tag"`in the file. Repeat the step for /blog and /category. Finally, change`baseurl: '/amp-affiliately-jekyll-theme'` correspondingly in the **_config.yml** file.

I'm not using the theme for project page
I'm using it for a repository  - shoaiyb.github.io

**Comment by shoaiyb** [comment]
How can I remove "check out my 19 referral codes" in the sidebar
![screenshot-here](https://user-images.githubusercontent.com/75518689/102538033-0d805980-40ac-11eb-825a-736b7961b550.jpg)

**Comment by shoaiyb** [comment]
And how can I remove the disclosures
![Screenshot_20201217-211017](https://user-images.githubusercontent.com/75518689/102538234-5506e580-40ac-11eb-9aa3-a0e14ff8cdb8.jpg)

**Comment by shoaiyb** [comment]
Is there anyway to remove redirect.viglink.com in the links
![Screenshot_20201217-211153](https://user-images.githubusercontent.com/75518689/102538438-8ed7ec00-40ac-11eb-9c9b-79e5b8dcf9a4.jpg)

**Comment by shoaiyb** [comment]
How can I remove your repository link when search 
![Screenshot_20201217-215906](https://user-images.githubusercontent.com/75518689/102543185-36f0b380-40b3-11eb-8e62-1a5902e682ff.jpg)

**Comment by chriskyfung** [comment]
> > Since I need the tag, blog, and category to be the base directory after my domain, the paths will mismatch if you're using the theme for a project page, e.g. yourname.github.io/repo123/.
> > 
> > Copy the file `/_layouts/default.html` to your Jekyll repository, and then replace `href="/tag/" to `href="{{site.baseurl}}/tag"`in the file. Repeat the step for /blog and /category. Finally, change`baseurl: '/amp-affiliately-jekyll-theme'` correspondingly in the **_config.yml** file.
> 
> I'm not using the theme for project page
> I'm using it for a repository  - [shoaiyb.github.io](https://dev.shoaiybsysa.ga)

Set the `baseurl: ''` in the _config.yml file.

**Comment by chriskyfung** [comment]
All the rest issues you asked can be changed by editing the HTML codes in the layout file **default.html**.
