### ISSUE TITLE
No pages creating for top nav menu

### ISSUE THREAD

**Issue by mrmikeceo** [chriskyfung/amp-affiliately-jekyll-theme#3]
Hello, could you pls help me with my issue. 
I install your perfect theme, but if i tried to go to nav menu links: /category/ /tag/  /cloud/ i got empty page..
![issue](https://user-images.githubusercontent.com/36260953/108567702-65884600-7311-11eb-9116-121aa8849b9d.jpg)

Shall i need to Add some .md files to root directory for this to work?
And one more question - could you please describe what it's for a file .post-template (in root directory)?)

**Comment by chriskyfung** [comment]
For you to easily implement the pages of category and tag lists, I have updated the theme and added their layout templates.
Please pull or download the latest version, and refer to [#enabling-lists-of-categories-and-tags](https://github.com/chriskyfung/amp-affiliately-jekyll-theme) in the updated README file.

Despite of this, you will still get an empty for /cloud/ until you assign a post to such category in the front matter.

Regarding the .post-template, please refer to the [jekyll-post Extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=rohgarg.jekyll-post) made by [Rohan Garg](https://marketplace.visualstudio.com/publishers/rohgarg).

**Comment by mrmikeceo** [comment]
Thank you its work! Now with Category and List all is ok)
But i still get empty (index page of folder) for http://127.0.0.1:4000/blog/ as i understood right, i need to add Blog folder (with index.html inside) and blog-list.html to _layouts folder. Is it right?)

**Comment by mrmikeceo** [comment]
Thank you for your quick response!
I wrote one more issue about these case, could you please help me with this?
Mike

**Comment by chriskyfung** [comment]
@mrmikeceo 

Update to the latest version and follow the steps of [#Enabling pagination for blog posts](Enabling Pagination for Blog Posts
) in the updated README file.

**Comment by chriskyfung** [comment]
@mrmikeceo I hope you'll enjoy blogging with this theme.
I would greatly appreciate it if you kindly give a tip for supporting me in its development.

<a href="https://www.buymeacoffee.com/chrisfungky"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: 41px !important;width: 174px !important;box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;-webkit-box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;" target="_blank"></a>

**Comment by mrmikeceo** [comment]
Already) Thank you!

**Comment by chriskyfung** [comment]
@mrmikeceo 
I made some modularization to the theme. I believe it will be better for you to customize your site.
For which parts you want to make changes, you can copy the corresponding files under the *_includes* directory to your own project. Then, editing the copied files. For example, you can remove a particular section in sidebar by deleting the codes in the _sidebar/sidebar-widget(#).html_. You can customize the footer by modifying the codes in _footer/footer-widget-col(#).html_.

**Comment by mrmikeceo** [comment]
Thank you!
It's great! If possible - i have one more suggestion. Could you please add
the possibility to have two dropdown menus on top navi?
Now if i tried to add a second dropdown item i got wrong scripts work. For
example when i click the first menu it expands ok. But when I immediately
click to second menu (without clicking to close to the first one) the
second menu does not open, but the first one close)
I tried to add a different ID to the first and second menu, but it
doesn't work.

PS
Menu code for my example:

           
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
                </li>

                <li class="nav-item dropdown" id="dropdown01">
                    <a class="nav-link dropdown-toggle"
on="tap:dropdown01.toggleClass(class='show'),navbar.toggleClass(class='show')"
href="#" data-toggle="dropdown" aria-haspopup="true"
aria-expanded="false">Blog</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="/blog/"><i class="far
fa-newspaper mr-2"></i>All Stories</a>
                    <a class="dropdown-item" href="/category/"><i
class="far fa-list-alt mr-2"></i>Categories</a>
                    <a class="dropdown-item" href="/tag/"><i class="fas
fa-tag mr-2"></i>Tags</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/about/">About</a>
                </li>

                <li class="nav-item dropdown" id="dropdown02">
                    <a class="nav-link dropdown-toggle"
on="tap:dropdown02.toggleClass(class='show'),navbar.toggleClass(class='show')"
href="#" data-toggle="dropdown" aria-haspopup="true"
aria-expanded="false">Products</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <a class="dropdown-item"
href="/products/agriculture/"><i class="fas fa-cannabis
mr-2"></i>Agriculture</a>
<a class="dropdown-item" href="/products/automotive/"><i class="fas
fa-car-alt mr-2"></i>Automotive & Transportation</a>
                    <a class="dropdown-item" href="/products/chemicals/"><i
class="fas fa-flask mr-2"></i>Chemicals</a>
<a class="dropdown-item" href="/products/construction/"><i class="fas
fa-hammer mr-2"></i>Construction</a>
<a class="dropdown-item" href="/products/home-care/"><i class="fas
fa-hand-holding-heart mr-2"></i>Home care</a>
<a class="dropdown-item" href="/products/dairy-industry/"><i class="fas
fa-fill mr-2"></i>Dairy industry</a>
<a class="dropdown-item" href="/products/brewing-industry/"><i class="fas
fa-wine-bottle mr-2"></i>Brewing industry</a>
<a class="dropdown-item" href="/products/veterinary/"><i class="fas fa-dog
mr-2"></i>Veterinary</a>
                    </div>
                </li>


                <li class="nav-item">
                    <button type="button" on="tap:amp-searchbar"
id="toggle-search" class="btn btn-primary" data-toggle="modal"
data-target="#searchbar"><i class="fas fa-search"></i></button>
                </li>
            </ul>

**Comment by chriskyfung** [comment]
@mrmikeceo Please check _main-nav/navigation.html_ in the update v1.4.3.
To produce the second dropdown, make a copy of the _dropdown-template.html_ and give it an appropriate filename.
Change the value of `dropdown_id` in the first line in the new file and add the items as you need.
Finally, add `{% include main-nav/<your-filename>.html %}` to where you want to place the second dropdown.

**Comment by mrmikeceo** [comment]
Thank you! Its real cool!!!
Unfortunately menu not collapses automatically and if you click to both
dropdowns you'll see it both opened simultaneously)

[image: image.png]

**Comment by chriskyfung** [comment]
It will need to replace the tap event with entirely CSS effects.
It'd take more time for me to debug.
If it is not critical, could you wait for the next major update?

**Comment by mrmikeceo** [comment]
Thank you! Its excellent theme! Yes, of course ill wait for big update from
you)

**Comment by chriskyfung** [comment]
@mrmikeceo Please update to the new Release v1.5.1 🚀
