### ISSUE TITLE
Tags and Categories are not working in `master`

### ISSUE THREAD

**Issue by philippescar** [chriskyfung/amp-affiliately-jekyll-theme#42]
Following the configuration guide the `categories` and `tags` are not being displayed or generated.

I also checked your `gh-pages` branch and it seems that both categories and tags are actually new pages, not something generated via jekyll.

**Comment by chriskyfung** [comment]
Please refer to https://chriskyfung.github.io/amp-affiliately-jekyll-theme/plugins/#-jekyll-archives

The `categories` and `tags` pages rely on the [jekyll/jekyll-archives: Archive pages for your Jekyll tags and categories.](https://github.com/jekyll/jekyll-archives) plugin, while this plugin is not [whitelisted in GitHub Pages](https://pages.github.com/versions/). They will not be created if you deploy the Jekyll directly using the default GitHub Actions workflow to build and deploy your site source files.

You need to use a custom GitHub Actions to work around. Please use the [`.github/workflows/deploy-jekyll.yml`](https://github.com/chriskyfung/amp-affiliately-jekyll-theme/blob/master/.github/workflows/deploy-jekyll.yml) as a template for configuring your own workflow.
